# Generated by Django 5.0.2 on 2024-03-09 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furniture_category', to='store.category'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='color',
            field=models.ManyToManyField(related_name='furniture_color', through='store.FurnitureColor', to='store.color'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furniture_company', to='store.company'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='material',
            field=models.ManyToManyField(related_name='furniture_material', through='store.FurnitureMaterial', to='store.material'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furniture_rating', to='store.rating'),
        ),
    ]
