# Generated by Django 5.0.2 on 2024-03-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_furniture_rating_alter_rating_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='furniturerating',
            unique_together={('furniture', 'rating')},
        ),
    ]
