---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Test
        run: docker-compose run --rm backend sh -c "pytest"
      - name: Lint
        run: docker-compose run --rm backend sh -c "flake8"
